import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import AnnouncementList from "@/components/AnnouncementList";
import Header from "@/components/Header";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/context/NextAuthProvider";
import { cn } from "@/lib/utils";

import "./globals.css";

const noto = Noto_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  variable: "--noto-sans",
});

export const metadata: Metadata = {
  title: "quiztory",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={cn(noto.className, "overflow-hidden")}>
          <div className="mx-auto flex max-w-6xl">
            <Header />
            <main className="flex min-h-screen w-full">
              <Separator orientation="vertical" />
              <div className="mt-5 w-full">{children}</div>

              <Separator orientation="vertical" />
              <AnnouncementList />
            </main>
          </div>
          <Toaster />
        </body>
      </NextAuthProvider>
    </html>
  );
}
